/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as Char123RoomIdChar125IndexRouteImport } from './routes/{-$roomId}.index'
import { Route as RoomRoomIdRouteImport } from './routes/room.$roomId'

const Char123RoomIdChar125IndexRoute =
  Char123RoomIdChar125IndexRouteImport.update({
    id: '/{-$roomId}/',
    path: '/{-$roomId}/',
    getParentRoute: () => rootRouteImport,
  } as any)
const RoomRoomIdRoute = RoomRoomIdRouteImport.update({
  id: '/room/$roomId',
  path: '/room/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/room/$roomId': typeof RoomRoomIdRoute
  '/{-$roomId}/': typeof Char123RoomIdChar125IndexRoute
}
export interface FileRoutesByTo {
  '/room/$roomId': typeof RoomRoomIdRoute
  '/{-$roomId}': typeof Char123RoomIdChar125IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/room/$roomId': typeof RoomRoomIdRoute
  '/{-$roomId}/': typeof Char123RoomIdChar125IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/room/$roomId' | '/{-$roomId}/'
  fileRoutesByTo: FileRoutesByTo
  to: '/room/$roomId' | '/{-$roomId}'
  id: '__root__' | '/room/$roomId' | '/{-$roomId}/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  RoomRoomIdRoute: typeof RoomRoomIdRoute
  Char123RoomIdChar125IndexRoute: typeof Char123RoomIdChar125IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/{-$roomId}/': {
      id: '/{-$roomId}/'
      path: '/{-$roomId}'
      fullPath: '/{-$roomId}/'
      preLoaderRoute: typeof Char123RoomIdChar125IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/room/$roomId': {
      id: '/room/$roomId'
      path: '/room/$roomId'
      fullPath: '/room/$roomId'
      preLoaderRoute: typeof RoomRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  RoomRoomIdRoute: RoomRoomIdRoute,
  Char123RoomIdChar125IndexRoute: Char123RoomIdChar125IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
